#!/bin/bash

touch 04_odd-numbers.js
touch 04_s.js
touch 05_multiples-of-3-and-5.js
touch 05_s.js
touch 06_print-multiples.js
touch 06_s.js
touch 07_fizzbuzz.js
touch 07_s.js
touch 08_prime-check.js
touch 08_s.js
touch 09_xor.js
touch 09_s.js
touch 10_guessing-the-password.js
touch 10_s.js
touch 11_student-grade.js
touch 11_s.js
touch 12_greatest-common-divisor.js
touch 12_s.js
touch 13_goldbach-numbers.js
touch 13_s.js
touch 14_pattern-generation.js
touch 14_s.js
touch 15_trimming-spaces.js
touch 15_s.js
touch 16_splitting-a-string.js
touch 16_s.js
touch 17_repeating-strings.js
touch 17_s.js
touch 18_string-starts-with.js
touch 18_s.js
touch 19_converting-strings-to-lower-case.js
touch 19_s.js
touch 20_substring-1.js
touch 20_s.js
touch 21_substring-2.js
touch 21_s.js
touch 22_code-review-rot13-cipher.js
touch 22_s.js
touch 23_index-of-substring.js
touch 23_s.js
touch 24_reference-solution-rot13-cipher.js
touch 24_s.js
touch 25_more-exercises.js
touch 25_s.js